# Default values for UDR.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}
  ## For unit test
  #nrf:
  #  addr: 10.233.102.4
  #dbServiceDomain: mongo.default.svc.free5gc.cluster.dev #mongo.default.svc.cluster.local

replicaCount: 1

image:
  repository: docker.io/alan0415/free5gc-ns-enabled #steven30801/free5gc-build
  tag: v3.2.1 #v2.0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

http:
  addr: 10.233.102.9 #192.168.2.9

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
