# Default values for amf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}
  ## For unit test
  #nrf:
  #  addr: 10.233.102.4
  #mnCoreBridge:
  #  subnet: 10.233.128.0/24

replicaCount: 1

image:
  repository: docker.io/alan0415/free5gc-ns-enabled
  tag: v3.2.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

http:
  addr: 10.233.102.2 #192.168.2.2
ngap:
  addr: 10.233.128.2 #192.168.3.2

podSecurityContext: {}

securityContext:
  privileged: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
