apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ransim.fullname" . }}
  labels:
    {{- include "ransim.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ransim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ransim.selectorLabels" . | nindent 8 }}
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.mgnt.addr }}\"]"
        k8s.v1.cni.cncf.io/networks: ransim-bridge-net
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-amf
          image: sequenceiq/busybox
          command: ['sh', '-c', 'while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" http://{{ .Values.amf.mgnt.addr }}:8000) -ne 404 ]; do echo waiting for dependencies; sleep 1; done']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: docker.io/alan0415/free5gc-ueransim:v3.2.1 #{{ include "ransim.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./nr-gnb"]
          args: ["-c", "./config/free5gc-gnb.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: gnb-config
              mountPath: /ueransim/config/free5gc-gnb.yaml
              subPath: free5gc-gnb.yaml
            - name: ue-config
              mountPath: /ueransim/config/free5gc-ue.yaml
              subPath: free5gc-ue.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: gnb-config
          configMap:
            name: ransim-configmap
            items:
            - key: free5gc-gnb.yaml
              path: free5gc-gnb.yaml
        - name: ue-config
          configMap:
            name: ransim-configmap
            items:
            - key: free5gc-ue.yaml
              path: free5gc-ue.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
