apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nrf.fullname" . }}
  labels:
    {{- include "nrf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nrf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nrf.selectorLabels" . | nindent 8 }}
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.http.addr }}\"]"
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "nrf.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["./nrf"]
          args: ["./nrf", "-c", "./config/nrfcfg.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: nrf-config
              mountPath: /free5gc/config/nrfcfg.yaml #/root/gofree5gc/config/nrfcfg.conf
              subPath: nrfcfg.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nrf-config
          configMap:
            name: nrf-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
