# Default values for nrf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}
  # Remove after unit test
  #dbServiceDomain: mongo.default.svc.cluster.local

replicaCount: 1

image:
  repository: docker.io/alan0415/free5gc-ns-enabled #docker.io/free5gc/nrf #steven30801/free5gc-build
  tag: v3.2.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

http:
  addr: 192.168.2.4

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
