apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udr.fullname" . }}
  labels:
    {{- include "udr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "udr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "udr.selectorLabels" . | nindent 8 }}
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.http.addr }}\"]"
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "udr.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./udr"]
          args: ["-c", "./config/udrcfg.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: udr-config
              mountPath: /free5gc/config/udrcfg.yaml
              subPath: udrcfg.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: udr-config
          configMap:
            name: udr-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
