apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webui.fullname" . }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webui.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "webui.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./webui"]
          args: ["-c", "./config/webuicfg.yaml"]
          #command: ["/bin/bash"]
          #args: ["-c", "cd webconsole && go run server.go -webuicfg webuicfg.conf"]
          ports:
            - name: webui
              containerPort: {{ .Values.service.webui.port }}
              protocol: TCP
          volumeMounts:
            - name: webui-config
              mountPath: /free5gc/config/webuicfg.yaml
              subPath: webuicfg.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webui-config
          configMap:
            name: webui-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
